config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"

  get "/search", to: "welcome#search"

  get "/favorites", to: "foods#favorites"

  resources :foods do
    member do
      post :add_to_favorites
      delete :remove_favorite
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    belongs_to :user
    belongs_to :food
  end
  

app/models/food.rb
class Food < ApplicationRecord
    has_many :favorites, dependent: :destroy
    has_many :users, through: :favorites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :favorites
         has_many :foods, through: :favorites

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
  
    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:account_update, keys: [:name])
    end
  end
  

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[ show edit update destroy ]


  # GET /foods or /foods.json
  def index
    @foods = Food.all
    
  end

  # GET /foods/1 or /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to food_url(@food), notice: "Food was successfully created." }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update

  
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: "Food was successfully updated." }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: "Food was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def add_to_favorites
    @food = Food.find(params[:id])
    current_user.foods << @food unless current_user.foods.include?(@food)
  
    redirect_to @food
    flash[:notice] = t('favorite_save')
  end
  

  def favorites 
    if current_user
      @foods = current_user.foods
    else 
      flash[:alert] = "Você precisa estar conectado para acessar os seus alimentos favoritos."

      redirect_to new_user_session_path # or wherever your sign in page is
    end
  end
  

# No seu controlador
def remove_favorite
  # Encontre o alimento e a associação com o usuário atual
  food = Food.find(params[:id])
  current_user.foods.delete(food)

  # Redirecione de volta para a página de favoritos com uma mensagem
  redirect_to favorites_path, notice: t('removed_favorites')
end








  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def food_params
      params.require(:food).permit(:name, :moisture, :kcal, :kj, :protein, :lipids, :cholesterol, :carbohydrates, :dietary_fiber, :ash, :calcium, :magnesium, :manganese, :phosphorus, :iron, :sodium, :potassium, :copper, :zinc, :retinol, :re, :rae, :thiamin, :riboflavin, :pyridoxine, :niacin, :vitamin_c, :image_url)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!, only: [:favorites]

    def index  
      end


      def search
        search_term = params[:q]
    
        if search_term.blank?
          redirect_to root_path
        else
          @foods = Food.where("CONVERT(name USING utf8) COLLATE utf8_general_ci LIKE ?", "%#{search_term}%")
        end
      end
      

  

end

app/helpers/application_helper.rb
module ApplicationHelper
    def bootstrap_class_for(flash_type)
        case flash_type
        when "alert"
          "danger"   # Green
        when "notice"
          "success"      # Blue
        else
          flash_type.to_s
        end
      end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/_food.html.erb
<div class="card mx-auto" style="width: 30rem;">
  <% image_url = food.image_url.present? ? food.image_url : 'https://w7.pngwing.com/pngs/205/731/png-transparent-default-avatar-thumbnail.png' %>
  <img src="<%= asset_path("#{image_url}") %>" class="card-img-top " alt="...">
  
  <div class="card-body">
    <h5 class="card-title"><%= food.name %> </h5>
    <ul>
      <li class="list-group-item">
        <strong><%= t('kcal')%></strong>
        <%= food.kcal.nil? ? 0 : food.kcal %>
      </li>
      <li class="list-group-item">
        <strong><%= t('protein')%></strong>
        <%= food.protein.nil? ? 0 : food.protein %>
      </li>
      <li class="list-group-item">
        <strong><%= t('carbohydrates')%></strong>
        <%= food.carbohydrates.nil? ? 0 : food.carbohydrates %>
      </li>
      <li class="list-group-item">
        <strong><%= t('lipids')%></strong>
        <%= food.lipids.nil? ? 0 : food.lipids %>
      </li>
    </ul>

  </div>
</div>

app/views/foods/_form.html.erb
       <div class="container">
         <%= link_to '< Voltar', food_path, class: 'btn btn-primary ' %>
            <div class="card mx-auto" style="width:40rem">
              <div class="card-header bg-primary text-white">
                <h2>Adicionar / Atualizar Alimento</h2>
              </div>
              <div class="card-body">
                <%= form_with(model: @food, html: {class: "needs-validation", novalidate: true}) do |form| %>
                  <div class="input-group mb-4">
                    <span class="input-group-text">Nome do Alimento</span>
                    <%= form.text_field :name, class: "form-control", id: "name", required: true %>
                  </div>
                  <% nutrient_fields = [
                    { name: :image_url, label: "Caminho da imagem" },
                    { name: :moisture, label: "Umidade" },
                    { name: :kcal, label: "Kcal" },
                    { name: :kj, label: "Kj" },
                    { name: :protein, label: "Proteína" },
                    { name: :lipids, label: "Lipídios" },
                    { name: :cholesterol, label: "Colesterol" },
                    { name: :carbohydrates, label: "Carboidratos" },
                    { name: :dietary_fiber, label: "Fibra Alimentar" },
                    { name: :ash, label: "Cinzas" },
                    { name: :calcium, label: "Cálcio" },
                    { name: :magnesium, label: "Magnésio" },
                    { name: :manganese, label: "Manganês" },
                    { name: :phosphorus, label: "Fósforo" },
                    { name: :iron, label: "Ferro" },
                    { name: :sodium, label: "Sódio" },
                    { name: :potassium, label: "Potássio" },
                    { name: :copper, label: "Cobre" },
                    { name: :zinc, label: "Zinco" },
                    { name: :retinol, label: "Retinol" },
                    { name: :re, label: "RE" },
                    { name: :rae, label: "RAE" },
                    { name: :thiamin, label: "Tiamina" },
                    { name: :riboflavin, label: "Riboflavina" },
                    { name: :pyridoxine, label: "Piridoxina" },
                    { name: :niacin, label: "Niacina" },
                    { name: :vitamin_c, label: "Vitamina C" }
                  ] %>
                  <% nutrient_fields.each do |field| %>
                    <div class="input-group mb-4">
                      <span class="input-group-text"><%= field[:label] %></span>
                      <%= form.text_field field[:name], class: "form-control", id: field[:name], required: true %>
                    </div>
                  <% end %>
                  <%= form.submit "Salvar", class: "btn btn-primary", data: {confirm: "Atualizar este alimento comprometerá a validade das informações no banco de dados. Deseja continuar mesmo assim?"} %>
                <% end %>
              </div>
            </div>
         
       </div>

app/views/foods/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: rgba(0, 0, 0, 0.7);">
  <div class="container-fluid">
    <%= link_to 'LOGO', root_path, class:"navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active text-white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Alimentos
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to 'Alimentos favoritos', favorites_path, class:"dropdown-item" %> </li>
            <li><a class="dropdown-item" href="#">Receitas</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Todos os alimentos', foods_path, class:"dropdown-item" %></li>
          </ul>
        </li>


        
      </ul>

<div>
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item d-flex align-items-center">
       
         <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registro', new_user_registration_path, class: 'nav-link text-white' %>
      </li>
    <% end %>
  </ul>
</div>








      

      
    </div>
  </div>
</nav>

app/views/foods/edit.html.erb
<%= render "form", food: @food %>

<br><br>

app/views/foods/favorites.html.erb
<%= stylesheet_link_tag 'home' %>


<div class='card mx-auto' style="width: 40rem;">
  <div class='card-header bg-dark text-white text-center'>
    <h1>Alimentos Favoritos</h1>
  </div>

  <div class= 'card-body' >
    <ul class="list-group list-group-flush">
      <% if @foods.blank? %>
        <li class="list-group-item text-center"><%= t('no_fav') %></li>
      <% else %>
        <% @foods.each do |food| %>
          <li class="list-group-item d-flex justify-content-between align-items-center">
            <%= link_to food.name, food_path(food) %>
            <%= link_to 'Remove from favorites', remove_favorite_food_path(food), method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/foods/index.html.erb
<%= stylesheet_link_tag 'home' %>


<div class="container mt-3">
  <p style="color: green"><%= notice %></p>
  
   <%= form_with(url: "/search", method: "get", class: "input-group mb-3 col-12 col-md-6") do %>
    <%= text_field_tag :q, nil, placeholder: "Procurar um alimento", class: "form-control", 'aria-label': "Procurar um Alimento:", 'aria-describedby': "button-addon2" %>
    <%= button_tag "Pesquisar", class: "btn btn-success", type: "submit", id: "button-addon2" %>
  <% end %>




   <ul class="list-group">
    <% @foods.each do |food| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
      
        <div>
          100g de: <%= food.name %>
          <div>Cálorias: <%= food.kcal.to_i %>Kcal</div>
          <div>Proteinas: <%=food.protein.nil? ? 0 : food.protein %>g</div>
          <div>Carboidratos: <%=food.carbohydrates.nil? ? 0 : food.carbohydrates %>g</div>
          <div>Lipidos: <%=food.lipids.nil? ? 0 : food.lipids %>g</div>
        </div>
        <%= link_to "Ver alimento", food, class: "ml-auto btn btn-primary" %>
      </li>
    <% end %>
  </ul>
  <br>
  <div class="container text-center" style="width:25rem"> <div class="alert alert-dark" role="alert">
  You have reached the end of the page!
</div></div>
  </div>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-8">
      <%= render @food %>





    </div>
    <div class="col-md-4">
    
       <div class="btn-group" role="group" aria-label="Basic mixed styles example">

   <%= link_to "Deletar alimento", @food, method: :delete, class: "btn btn-danger", data: { confirm: 'Tem certeza que deseja destruir esta comida?' }%>
  <%= link_to 'Adicionar aos Favoritos', add_to_favorites_food_path(@food), method: :post, class: "btn btn-success", data: {alert:"alerta"} %>
  </div>  
  

<br><br>
   <div class="btn-group" role="group" aria-label="Basic mixed styles example">
  <%= link_to "Editar alimento", edit_food_path(@food), method: :get, class: "btn btn-warning", data: {confirm: "Não é recomendado modificar os nutrientes do alimento, deseja continuar?"}%> 
  <%= link_to "Voltar para tela principal", root_path, method: :get, class: "btn btn-secondary" %>
  
</div>  
<br><br>
  <%= form_for @food do |f| %>
    <%= f.label :image_url %>:
    <%= f.text_field :image_url %><br />
  
  
  
    <%= f.submit %>
  <% end %>



    </div>
    
  </div>
  

</div>



                 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComidasApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag 'application' %>
    <%= render 'header' %>

  </head>


  <body>

<div class="mx-auto my-5 text-center" style="width: 18rem;">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= bootstrap_class_for(message_type) %>">
          <%= message %>
         </div>
          </div>
        <% end %>
    
    </div>

      <%= yield %>
  </body>
</html>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: rgba(0, 0, 0, 0.7);">
  <div class="container-fluid">
    <%= link_to 'LOGO', root_path, class:"navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: "nav-link active text-white" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle text-white" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Alimentos
          </a>
          <ul class="dropdown-menu">
            <li> <%= link_to 'Alimentos favoritos', favorites_path, class:"dropdown-item" %> </li>
            <li><a class="dropdown-item" href="#">Receitas</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to 'Todos os alimentos', foods_path, class:"dropdown-item" %></li>
          </ul>
        </li>


        
      </ul>

<div>
  <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li class="nav-item d-flex align-items-center">
       
         <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to 'Login', new_user_session_path, class: 'nav-link text-white' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registro', new_user_registration_path, class: 'nav-link text-white' %>
      </li>
    <% end %>
  </ul>
</div>








      

      
    </div>
  </div>
</nav>

app/views/welcome/index.html.erb
<%= stylesheet_link_tag 'home' %>



<% if user_signed_in? %>





<div class="container" style="margin-top: 150px;"><h1>Alimentos & Nutrientes </h1></div>

<div class="container mt-5 d-flex align-items-center justify-content-center">



  <%= form_with(url: "/search", method: "get", class: "input-group mb-3 col-12 col-md-6") do %>
    <%= text_field_tag :q, nil, placeholder: "Procurar um alimento", class: "form-control", 'aria-label': "Procurar um Alimento:", 'aria-describedby': "button-addon2" %>
    <%= button_tag "Pesquisar", class: "btn btn-success", type: "submit", id: "button-addon2" %>
  <% end %>




</div>

<div class="card mx-auto" style="width:18rem "> 
<div class="card-header text-center">   <%=current_user.name%>    <%= bootstrap_icon "check", width: 50, height: 50, fill: "green" %>
   </div>
  <div class="card-body">  <%= link_to 'Editar Usuário', edit_user_registration_path %>  </div>

</div>






  
<% else %>


  

<div class="container"style="margin-top: 150px;"><h1>Alimentos & Nutrientes</h1></div>

<div class="container mt-5 d-flex align-items-center justify-content-center">



  <%= form_with(url: "/search", method: "get", class: "input-group mb-3 col-12 col-md-6") do %>
    <%= text_field_tag :q, nil, placeholder: "Procurar um alimento", class: "form-control", 'aria-label': "Procurar um Alimento:", 'aria-describedby': "button-addon2" %>
    <%= button_tag "Pesquisar", class: "btn btn-success", type: "submit", id: "button-addon2" %>
  <% end %>


<% end %>

app/views/welcome/search.html.erb
<%= stylesheet_link_tag 'home' %>

<div class="container">
  <h1 class="text-center">Resultados da Pesquisa</h1>
  
  <%= form_with(url: "/search", method: "get", class: "input-group mb-3 col-12 col-md-6") do %>
    <%= text_field_tag :q, nil, placeholder: "Procurar outro alimento", class: "form-control", 'aria-label': "Procurar um Alimento:", 'aria-describedby': "button-addon2" %>
    <%= button_tag "Pesquisar", class: "btn btn-success", type: "submit", id: "button-addon2" %>
  <% end %>
  <br><br>
 <% if @foods.any? %>
  <ul class="list-group">
    <% @foods.each do |food| %>
      <li class="list-group-item d-flex justify-content-between align-items-center">
      
        <div>
          100g de: <%= food.name %>
          <div>Cálorias: <%= food.kcal.to_i %>Kcal</div>
          <div>Proteinas: <%=food.protein.nil? ? 0 : food.protein %>g</div>
          <div>Carboidratos: <%=food.carbohydrates.nil? ? 0 : food.carbohydrates %>g</div>
          <div>Lipidos: <%=food.lipids.nil? ? 0 : food.lipids %>g</div>
        </div>
        <%= link_to "Ver alimento", food, class: "ml-auto btn btn-primary" %>
      </li>
    <% end %>
  </ul>
  <% else %>
  
  <%flash.alert = "Alimento não encontrado"%>
  
   <% end %>
</div>